//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListSwype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customlist
    {
        public customlist()
        {
            this.userlists = new HashSet<userlist>();
        }
    
        public int id { get; set; }
        public int userid { get; set; }
        public string itemname { get; set; }
        public string itemimage { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<userlist> userlists { get; set; }
    }
}
