//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListSwype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.customlists = new HashSet<customlist>();
            this.userconnections = new HashSet<userconnection>();
            this.userconnections1 = new HashSet<userconnection>();
            this.userlists = new HashSet<userlist>();
            this.userlocations = new HashSet<userlocation>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<customlist> customlists { get; set; }
        public virtual ICollection<userconnection> userconnections { get; set; }
        public virtual ICollection<userconnection> userconnections1 { get; set; }
        public virtual ICollection<userlist> userlists { get; set; }
        public virtual ICollection<userlocation> userlocations { get; set; }
    }
}
